### ISSUE TITLE
Add tag to represent a "stable" version for ease of packaging

### ISSUE THREAD

**Issue by graysky2** [MTDL9/vim-log-highlighting#9]
Please add a tag to package managers can easily grab without forking.

```
tag=v1.0
git tag $tag -m "$tag" && git push --tags
```

**Comment by MTDL9** [comment]
Hello,
sorry for the response delay. I created a tag "v1.0.0" with the initial stable release
https://github.com/MTDL9/vim-log-highlighting/releases/tag/v1.0.0

The package managers I tried (Vim Plug, Vundle, Pathogen) all work fine without requiring a fork of the master, however I agree it's better to have tags if someone wants to point to a stable release.

Closing this as resolved, feel free to comment if you need something else and I'll reopen this.
